# Generated by Django 4.2 on 2023-07-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel916', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticebord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
